// ── Constants ──
export const DISTRIBUTOR_TESTNET = "CBRCYVQESTGALAPH4M2275HWLJUWYKCPCK4TNFHH63J3LSYBFQLYFUI4";
export const DISTRIBUTOR_MAINNET = "CD5Q6Z3..."  // TODO: mainnet contract address

// Soroswap testnet tokens
export const TESTNET_XLM = "CDLZFC3SYJYDZT7K67VZ75HPJVIEUVNIXF47ZG2FB2RMQQVU2HHGCYSC";
export const TESTNET_BLEND_USDC = "CAQCFVLOBK5GIULPNZRGATJJMIZL5BSP7X5YJVMGCPTUEPFM4AVSRCJU";
export const TESTNET_BLND_USDC = "CB22KRA3YZVCNCQI64JQ5WE7UY2VAV7WFLK6A2JN3HEX56T2EDAFO7QF";
export const TESTNET_BLEND_WETH = "CAZAQB3D7KSLSNOSQKYD2V4JP5V2Y3B4RDJZRLBFCCIXDCTE3WHSY3UE";
export const TESTNET_BLEND_WBTC = "CAP5AMC2OHNVREO66DFIN6DHJMPOBAJ2KCDDIMFBR7WWJH5RZBFM3UEI";

// DeFindex API
export const DEFINDEX_API_URL = "https://api.defindex.io";
export const TESTNET_CONTRACTS_URL = "https://raw.githubusercontent.com/paltalabs/defindex/refs/heads/main/public/testnet.contracts.json";

