// ── Constants ──
export const DISTRIBUTOR_TESTNET = "CCKCWJS2PN3O7EQCRGWQLM3EB2W2QK37ZPZX4KWTT43OFYUTKEP4AGPP"; // verified version
export const DISTRIBUTOR_MAINNET = "CDQ7KXPQHSGEBWQ5HQEOTMEZ45ODZPU3UTY3GC4GOMHOCQ7J35ZIVVIN"  // verified version

// Soroswap testnet tokens
export const TESTNET_XLM = "CDLZFC3SYJYDZT7K67VZ75HPJVIEUVNIXF47ZG2FB2RMQQVU2HHGCYSC";
export const TESTNET_BLEND_USDC = "CAQCFVLOBK5GIULPNZRGATJJMIZL5BSP7X5YJVMGCPTUEPFM4AVSRCJU";
export const TESTNET_BLND_USDC = "CB22KRA3YZVCNCQI64JQ5WE7UY2VAV7WFLK6A2JN3HEX56T2EDAFO7QF";
export const TESTNET_BLEND_WETH = "CAZAQB3D7KSLSNOSQKYD2V4JP5V2Y3B4RDJZRLBFCCIXDCTE3WHSY3UE";
export const TESTNET_BLEND_WBTC = "CAP5AMC2OHNVREO66DFIN6DHJMPOBAJ2KCDDIMFBR7WWJH5RZBFM3UEI";

// DeFindex API
export const DEFINDEX_API_URL = "https://api.defindex.io";
export const TESTNET_CONTRACTS_URL = "https://raw.githubusercontent.com/paltalabs/defindex/refs/heads/main/public/testnet.contracts.json";

